// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dveopivlmmijgxrgpwdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2ZW9waXZsbW1pamd4cmdwd2RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDE3MjcsImV4cCI6MjA2MDAxNzcyN30.XbjEMJJ26oXZhXaPjbp0FaLhzO6E-uwyxZPYw7GjDak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);